### ISSUE TITLE
ODBC Example

### ISSUE THREAD

**Issue by lethjakman** [gbwey/persistent-odbc#11]
I see that this project allows for ODBC support with persistent, but I can't seem to figure out how to configure it to work with Oracle. Is there any chance we could get some simple example database connection's?

**Comment by gbwey** [comment]
Hi,
Take a look at TestOne.hs or Test1.hs or TestODBC.hs in the examples directory. For the oracle case, create a valid odbc connection and call it "oracle_test". This is just what the examples use so you can change this to whatever you want. Are you asking how to create an odbc connection? If so, are you on windows or unix? Let me know how I can help.
Best,
Grant
