### ISSUE TITLE
compatibility with new persistent and resoucet

### ISSUE THREAD

**Issue by zilinc** [gbwey/persistent-odbc#20]
Some of the functions from these libraries have changed to the `MonadUnliftIO`constraint from the old `MonadBaseControl`. `ExceptT` is not an instance of the former, hence the package doesn't compile against the newer dependencies. `resourcet` should be `< 1.2` and `persistent < 2.8` for the current master.

**Comment by gbwey** [comment]
upgraded to us monadunliftio
